# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/page/userguide/cmd_ci.html >
#
language: python
python:
- '2.7'
sudo: false
env:
  - PIO_ENV=openevse
  - PIO_ENV=openevse_slow
  - PIO_ENV=openevse_ota
  - PIO_ENV=openevse
    PLATFORMIO_BUILD_FLAGS=-DENABLE_DEBUG
  - PIO_ENV=openevse
    PLATFORMIO_BUILD_FLAGS=-DENABLE_DEBUG -DENABLE_PROFILE
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- platformio run -e $PIO_ENV
